<?xml version="1.0" encoding="UTF-8"?>
<cpp:CppNamespace xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cpp="http://www.dfki.de/SPECifIC/emf/2015/cpp" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="cpp" nsURI="http://www.dfki.de/SPECifIC/cpp">
  <eClassifiers xsi:type="ecore:EDataType" name="void"/>
  <eClassifiers xsi:type="ecore:EDataType" name="bool"/>
  <eClassifiers xsi:type="ecore:EDataType" name="signed char"/>
  <eClassifiers xsi:type="ecore:EDataType" name="unsigned char"/>
  <eClassifiers xsi:type="ecore:EDataType" name="char"/>
  <eClassifiers xsi:type="ecore:EDataType" name="wchar_t"/>
  <eClassifiers xsi:type="ecore:EDataType" name="char16_t"/>
  <eClassifiers xsi:type="ecore:EDataType" name="char32_t"/>
  <eClassifiers xsi:type="ecore:EDataType" name="short int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="unsigned short int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="unsigned int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="long int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="unsigned long int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="long long int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="unsigned long long int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="float"/>
  <eClassifiers xsi:type="ecore:EDataType" name="double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="long double"/>
</cpp:CppNamespace>
