<?xml version="1.0" encoding="UTF-8"?>
<cpp:CppNamespace xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cpp="http://www.dfki.de/SPECifIC/emf/2015/cpp" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="sc_dt" nsURI="http://www.dfki.de/SPECifIC/systemc/sc_dt">
  <eClassifiers xsi:type="ecore:EEnum" name="sc_numrep">
    <eLiterals name="SC_NOBASE"/>
    <eLiterals name="SC_BIN"/>
    <eLiterals name="SC_OCT"/>
    <eLiterals name="SC_DEC"/>
    <eLiterals name="SC_HEX"/>
    <eLiterals name="SC_BIN_US"/>
    <eLiterals name="SC_BIN_SM"/>
    <eLiterals name="SC_OCT_US"/>
    <eLiterals name="SC_OCT_SM"/>
    <eLiterals name="SC_HEX_US"/>
    <eLiterals name="SC_HEX_SM"/>
    <eLiterals name="SC_CSD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_enc">
    <eLiterals name="SC_TC_"/>
    <eLiterals name="SC_US_"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_q_mode">
    <eLiterals name="SC_RND"/>
    <eLiterals name="SC_RND_ZERO"/>
    <eLiterals name="SC_RND_MIN_INF"/>
    <eLiterals name="SC_RND_INF"/>
    <eLiterals name="SC_RND_CONV"/>
    <eLiterals name="SC_TRN"/>
    <eLiterals name="SC_TRN_ZERO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_o_mode">
    <eLiterals name="SC_SAT"/>
    <eLiterals name="SC_SAT_ZERO"/>
    <eLiterals name="SC_SAT_SYM"/>
    <eLiterals name="SC_WRAP"/>
    <eLiterals name="SC_WRAP_SM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_switch">
    <eLiterals name="SC_OFF"/>
    <eLiterals name="SC_ON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_fmt">
    <eLiterals name="SC_F"/>
    <eLiterals name="SC_E"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="scfx_ieee_double">
    <eOperations xsi:type="cpp:CppOperation" name="negative" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="exponent" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="mantissa0" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="mantissa1" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_inf" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_nan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="nan" eType="#//scfx_ieee_double"
        visibility="public" static="true"/>
    <eOperations xsi:type="cpp:CppOperation" name="inf" eType="#//scfx_ieee_double"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_id"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="scfx_ieee_float">
    <eOperations xsi:type="cpp:CppOperation" name="negative" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="exponent" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="mantissa" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_inf" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_nan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_if"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_bit">
    <eOperations xsi:type="cpp:CppOperation" name="invalid_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        static="true"/>
    <eOperations xsi:type="cpp:CppOperation" name="invalid_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        static="true"/>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="c" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//char"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="b" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//unsigned%20int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//long%20int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//unsigned%20long%20int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" typedef="#//int64"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" typedef="#//uint64"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_val" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        visibility="private"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_logic_value_t">
    <eLiterals name="Log_0"/>
    <eLiterals name="Log_1"/>
    <eLiterals name="Log_Z"/>
    <eLiterals name="Log_X"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_logic">
    <eOperations xsi:type="cpp:CppOperation" name="invalid_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private" static="true"/>
    <eOperations xsi:type="cpp:CppOperation" name="invalid_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private" static="true"/>
    <eOperations xsi:type="cpp:CppOperation" name="invalid_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private" static="true"/>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="#//sc_logic_value_t"
        visibility="private" static="true">
      <eParameters xsi:type="cpp:CppParameter" name="v" eType="#//sc_logic_value_t"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="#//sc_logic_value_t"
        visibility="private" static="true">
      <eParameters xsi:type="cpp:CppParameter" name="b" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="#//sc_logic_value_t"
        visibility="private" static="true">
      <eParameters xsi:type="cpp:CppParameter" name="c" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//char"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="to_value" eType="#//sc_logic_value_t"
        visibility="private" static="true">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="char_to_logic" eType="#//sc_logic_value_t"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="logic_to_char" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//char"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="and_table" eType="#//sc_logic_value_t"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="or_table" eType="#//sc_logic_value_t"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="xor_table" eType="#//sc_logic_value_t"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="not_table" eType="#//sc_logic_value_t"
        visibility="public" static="true"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_val" eType="#//sc_logic_value_t"
        visibility="private"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_value_base"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_generic_base">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_global">
    <eTypeParameters name="T"/>
    <eOperations xsi:type="cpp:CppOperation" name="update" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_instance" visibility="private"
        static="true">
      <eGenericType eClassifier="#//sc_global">
        <eTypeArguments eTypeParameter="#//sc_global/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_map" visibility="private">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_phash">
        <eTypeArguments eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
        <eTypeArguments eTypeParameter="#//sc_global/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_proc" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_value_ptr" visibility="private">
      <eGenericType eTypeParameter="#//sc_global/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_context">
    <eTypeParameters name="T"/>
    <eOperations xsi:type="cpp:CppOperation" name="begin" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="end" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_value" visibility="private">
      <eGenericType eTypeParameter="#//sc_context/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_def_value_ptr" visibility="private">
      <eGenericType eTypeParameter="#//sc_context/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_old_value_ptr" visibility="private">
      <eGenericType eTypeParameter="#//sc_context/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_without_context"/>
  <eClassifiers xsi:type="ecore:EEnum" name="sc_context_begin">
    <eLiterals name="SC_NOW"/>
    <eLiterals name="SC_LATER"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_length_param">
    <eOperations xsi:type="cpp:CppOperation" name="len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="private"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_unsigned_bitref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="index_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_index" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_unsigned_bitref" eSuperTypes="#//sc_unsigned_bitref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_unsigned_bitref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_unsigned_subref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="left_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="right_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_left" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_right" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_unsigned_subref" eSuperTypes="#//sc_unsigned_subref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_unsigned_subref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_unsigned" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clear" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="v" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="invert" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="reverse" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_packed_rep" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="buf" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="copy_digits" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private">
      <eParameters xsi:type="cpp:CppParameter" name="nb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="nd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="d" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="makezero" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eOperations xsi:type="cpp:CppOperation" name="convert_2C_to_SM" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eOperations xsi:type="cpp:CppOperation" name="convert_SM_to_2C_to_SM" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eOperations xsi:type="cpp:CppOperation" name="convert_SM_to_2C" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_unsigned"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="sgn" visibility="private"
        typedef="#//small_type"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="nbits" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="ndigits" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="digit" visibility="private"
        typedef="#//sc_digit"/>
    <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        name="elemtype"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_signed_bitref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="index_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_index" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_signed_bitref" eSuperTypes="#//sc_signed_bitref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_signed_bitref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_signed_subref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="left_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="right_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_left" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_right" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_signed_subref" eSuperTypes="#//sc_signed_subref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_signed_subref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_signed" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clear" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="v" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="invert" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="reverse" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_packed_rep" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="buf" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="copy_digits" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private">
      <eParameters xsi:type="cpp:CppParameter" name="nb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="nd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="d" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="makezero" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eOperations xsi:type="cpp:CppOperation" name="convert_2C_to_SM" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eOperations xsi:type="cpp:CppOperation" name="convert_SM_to_2C_to_SM" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eOperations xsi:type="cpp:CppOperation" name="convert_SM_to_2C" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="sgn" visibility="private"
        typedef="#//small_type"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="nbits" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="ndigits" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="private"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="digit" visibility="private"
        typedef="#//sc_digit"/>
    <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"
        name="elemtype"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_uint_bitref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="index_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_index" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_uint_bitref" eSuperTypes="#//sc_uint_bitref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_uint_bitref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_uint_subref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="left_i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="right_i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_left" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_right" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_uint_subref" eSuperTypes="#//sc_uint_subref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_uint_subref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_uint_base" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="extend_sign" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="v" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_val" visibility="public"
        typedef="#//uint_type"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_ulen" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_int_bitref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="index_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_index" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_int_bitref" eSuperTypes="#//sc_int_bitref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_int_bitref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_int_subref_r" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="initialize" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="obj_p"/>
      <eParameters xsi:type="cpp:CppParameter" name="left_i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="right_i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_left" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj_p" visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_right" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_int_subref" eSuperTypes="#//sc_int_subref_r">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_int_subref"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_int_base" eSuperTypes="#//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="extend_sign" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="v" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_val" visibility="public"
        typedef="#//int_type"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_ulen" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_proxy">
    <eTypeParameters name="X"/>
    <eOperations xsi:type="cpp:CppOperation" name="bit" visibility="public">
      <eGenericType eClassifier="#//sc_bitref">
        <eTypeArguments eTypeParameter="#//sc_proxy/X"/>
      </eGenericType>
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="range" visibility="public">
      <eGenericType eClassifier="#//sc_subref">
        <eTypeArguments eTypeParameter="#//sc_proxy/X"/>
      </eGenericType>
      <eParameters xsi:type="cpp:CppParameter" name="hi" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="lo" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_bitref_r">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj" visibility="public">
      <eGenericType eTypeParameter="#//sc_bitref_r/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_index" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_bitref">
    <eTypeParameters name="X"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_bit" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="n" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="value" eType="#//sc_logic_value_t"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_word" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_cword" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clean_tail" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_subref_r">
    <eTypeParameters name="X"/>
    <eOperations xsi:type="cpp:CppOperation" name="check_bounds" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_bit" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="n" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="value" eType="#//sc_logic_value_t"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_word" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_cword" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clean_tail" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_obj" visibility="public">
      <eGenericType eTypeParameter="#//sc_subref_r/X"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_hi" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_lo" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_subref">
    <eTypeParameters name="X"/>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <typedefs eClassifier="#//sc_subref_r" name="base_type" visibility="public">
      <eTypeArguments eTypeParameter="#//sc_subref/X"/>
    </typedefs>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_concref_r">
    <eTypeParameters name="X"/>
    <eTypeParameters name="Y"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_bit" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="n" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="value" eType="#//sc_logic_value_t"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_word" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_cword" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clean_tail" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_left" visibility="public">
      <eGenericType eTypeParameter="#//sc_concref_r/X"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_right" visibility="public">
      <eGenericType eTypeParameter="#//sc_concref_r/Y"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_delete" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_refs" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_concref">
    <eTypeParameters name="X"/>
    <eTypeParameters name="Y"/>
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <typedefs eClassifier="#//sc_concref_r" name="base_type" visibility="public">
      <eTypeArguments eTypeParameter="#//sc_concref/X"/>
      <eTypeArguments eTypeParameter="#//sc_concref/Y"/>
    </typedefs>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_proxy_traits"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_mixed_proxy_traits_helper" eSuperTypes="#//sc_proxy_traits"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_bv_base" eSuperTypes="#//sc_proxy">
    <eOperations xsi:type="cpp:CppOperation" name="init" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="length_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="assign_from_string" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_bit" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="value" eType="#//sc_logic_value_t"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_word" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_cword" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clean_tail" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_size" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_data" visibility="public"
        typedef="#//sc_digit"/>
    <typedefs eClassifier="#//sc_proxy" name="base_type" visibility="public">
      <eTypeArguments eClassifier="#//sc_bv_base"/>
    </typedefs>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_lv_base" eSuperTypes="#//sc_proxy">
    <eOperations xsi:type="cpp:CppOperation" name="init" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void">
      <eParameters xsi:type="cpp:CppParameter" name="length_" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="assign_from_string" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"/>
    <eOperations xsi:type="cpp:CppOperation" name="set_bit" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="i" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="value" eType="#//sc_logic_value_t"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_word" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="wi" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="set_cword" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="wi" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
      <eParameters xsi:type="cpp:CppParameter" name="w" typedef="#//sc_digit"/>
    </eOperations>
    <eOperations xsi:type="cpp:CppOperation" name="clean_tail" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_size" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_data" visibility="public"
        typedef="#//sc_digit"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_ctrl" visibility="public"
        typedef="#//sc_digit"/>
    <typedefs eClassifier="#//sc_proxy" name="base_type" visibility="public">
      <eTypeArguments eClassifier="#//sc_lv_base"/>
    </typedefs>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_lv" eSuperTypes="#//sc_lv_base"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_bv" eSuperTypes="#//sc_bv_base"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_bigint" eSuperTypes="#//sc_signed"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_biguint" eSuperTypes="#//sc_unsigned"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_int" eSuperTypes="#//sc_int_base"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_uint" eSuperTypes="#//sc_uint_base"/>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_concatref" eSuperTypes="#//sc_generic_base #//sc_value_base">
    <eOperations xsi:type="cpp:CppOperation" name="scan" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
        visibility="public">
      <eParameters xsi:type="cpp:CppParameter" name="is"/>
    </eOperations>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" visibility="public"
        static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_concatref"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_left_p" eType="#//sc_value_base"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_right_p" eType="#//sc_value_base"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_len_r" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
        visibility="public"/>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_flags" visibility="public"/>
  </eClassifiers>
  <eClassifiers xsi:type="cpp:CppClass" name="sc_concat_bool" eSuperTypes="#//sc_value_base">
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_pool" static="true">
      <eGenericType eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/systemc/sc_core#//sc_vpool">
        <eTypeArguments eClassifier="#//sc_concat_bool"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="cpp:CppAttribute" name="m_value" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//bool"/>
  </eClassifiers>
  <typedefs eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/cpp/std#//basic_istream"
      name="systemc_istream">
    <eTypeArguments eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//char"/>
  </typedefs>
  <typedefs eClassifier="cpp:CppClass http://www.dfki.de/SPECifIC/cpp/std#//basic_ostream"
      name="systemc_ostream">
    <eTypeArguments eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//char"/>
  </typedefs>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//unsigned%20char"
      name="uchar"/>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int" name="small_type"/>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//unsigned%20int"
      name="sc_digit"/>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//long%20long%20int"
      name="int64"/>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//unsigned%20long%20long%20int"
      name="uint64"/>
  <typedefs eClassifier="ecore:EEnum http://www.dfki.de/SPECifIC/cpp/std#//_Ios_Fmtflags"
      name="fmtflags"/>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//long%20long%20int"
      name="int_type"/>
  <typedefs eClassifier="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//unsigned%20long%20long%20int"
      name="uint_type"/>
  <typedefs eClassifier="#//sc_context" name="sc_length_context">
    <eTypeArguments eClassifier="#//sc_length_param"/>
  </typedefs>
  <operations name="to_string" static="true"/>
  <operations name="to_string" static="true"/>
  <operations name="to_string" static="true"/>
  <operations name="to_string" static="true"/>
  <operations name="to_string" static="true"/>
  <operations name="to_string" static="true"/>
  <operations name="div_on_help_signed" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
      static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="div_on_help_unsigned" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//void"
      static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="compare_unsigned" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"
      static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="add_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="sub_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="mul_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="s" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="div_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="s" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="mod_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="and_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="or_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="xor_unsigned_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="add_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="sub_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="mul_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="s" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="div_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="s" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="mod_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="and_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="or_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="xor_signed_friend" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="us" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="unb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="und" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="ud" typedef="#//sc_digit"/>
    <eParameters xsi:type="cpp:CppParameter" name="vs" typedef="#//small_type"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnb" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vnd" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//int"/>
    <eParameters xsi:type="cpp:CppParameter" name="vd" typedef="#//sc_digit"/>
  </operations>
  <operations name="convert_to_bin" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="s" eType="ecore:EDataType http://www.dfki.de/SPECifIC/cpp#//char"/>
  </operations>
  <operations name="convert_to_fmt" static="true">
    <eParameters xsi:type="cpp:CppParameter" name="s"/>
    <eParameters xsi:type="cpp:CppParameter" name="numrep" eType="#//sc_numrep"/>
  </operations>
</cpp:CppNamespace>
