<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:ocl.ecore="http://www.eclipse.org/ocl/1.1.0/Ecore">
  <ecore:EPackage name="acs">
    <eClassifiers xsi:type="ecore:EClass" name="Building"/>
    <eClassifiers xsi:type="ecore:EClass" name="Person">
      <eOperations name="pass">
        <eParameters name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aut" upperBound="-1"
          eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sit" lowerBound="1" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"/>
    </eClassifiers>
  </ecore:EPackage>
  <ocl.ecore:Variable name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
  <ecore:EPackage name="collections">
    <eClassifiers xsi:type="ocl.ecore:OrderedSetType" instanceClassName="java.util.LinkedHashSet"
        elementType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"/>
    <eClassifiers xsi:type="ocl.ecore:SetType" instanceClassName="java.util.Set" elementType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"/>
  </ecore:EPackage>
  <ocl.ecore:Variable name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
  <ocl.ecore:Variable name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
      representedParameter="ecore:EParameter /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass/b"/>
  <ocl.ecore:Variable name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
  <ocl.ecore:Constraint name="P5" constrainedElements="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"
      stereotype="invariant">
    <specification xsi:type="ocl.ecore:ExpressionInOCL">
      <bodyExpression xsi:type="ocl.ecore:OperationCallExp" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean"
          referredOperation="ecore:EOperation http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OrderedSet(T)_Class/includes">
        <source xsi:type="ocl.ecore:PropertyCallExp" eType="ocl.ecore:OrderedSetType /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/2/OrderedSet(Building)"
            referredProperty="ecore:EReference /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/aut">
          <source xsi:type="ocl.ecore:VariableExp" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"
              referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/6/@specification/@contextVariable"/>
        </source>
        <argument xsi:type="ocl.ecore:PropertyCallExp" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
            referredProperty="ecore:EReference /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/sit">
          <source xsi:type="ocl.ecore:VariableExp" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"
              referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/6/@specification/@contextVariable"/>
        </argument>
      </bodyExpression>
      <contextVariable xsi:type="ocl.ecore:Variable" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
    </specification>
  </ocl.ecore:Constraint>
  <ocl.ecore:Constraint name="pass_pre1a" constrainedElements="ecore:EOperation /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass"
      stereotype="precondition">
    <specification xsi:type="ocl.ecore:ExpressionInOCL">
      <bodyExpression xsi:type="ocl.ecore:OperationCallExp" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean"
          referredOperation="ecore:EOperation http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OrderedSet(T)_Class/includes">
        <source xsi:type="ocl.ecore:PropertyCallExp" eType="ocl.ecore:OrderedSetType /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/2/OrderedSet(Building)"
            referredProperty="ecore:EReference /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/aut">
          <source xsi:type="ocl.ecore:VariableExp" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"
              referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/7/@specification/@contextVariable"/>
        </source>
        <argument xsi:type="ocl.ecore:VariableExp" name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
            referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/7/@specification/@parameterVariable.0"/>
      </bodyExpression>
      <contextVariable xsi:type="ocl.ecore:Variable" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
      <parameterVariable xsi:type="ocl.ecore:Variable" name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
          representedParameter="ecore:EParameter /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass/b"/>
    </specification>
  </ocl.ecore:Constraint>
  <ocl.ecore:Constraint name="pass_pre2a" constrainedElements="ecore:EOperation /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass"
      stereotype="precondition">
    <specification xsi:type="ocl.ecore:ExpressionInOCL">
      <bodyExpression xsi:type="ocl.ecore:OperationCallExp" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean"
          referredOperation="ecore:EOperation http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclAny_Class/%3C%3E">
        <source xsi:type="ocl.ecore:PropertyCallExp" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
            referredProperty="ecore:EReference /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/sit">
          <source xsi:type="ocl.ecore:VariableExp" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"
              referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/8/@specification/@contextVariable"/>
        </source>
        <argument xsi:type="ocl.ecore:VariableExp" name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
            referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/8/@specification/@parameterVariable.0"/>
      </bodyExpression>
      <contextVariable xsi:type="ocl.ecore:Variable" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
      <parameterVariable xsi:type="ocl.ecore:Variable" name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
          representedParameter="ecore:EParameter /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass/b"/>
    </specification>
  </ocl.ecore:Constraint>
  <ocl.ecore:Constraint name="pass_posta" constrainedElements="ecore:EOperation /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass"
      stereotype="postcondition">
    <specification xsi:type="ocl.ecore:ExpressionInOCL">
      <bodyExpression xsi:type="ocl.ecore:OperationCallExp" eType="ocl.ecore:PrimitiveType http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/Boolean"
          referredOperation="ecore:EOperation http://www.eclipse.org/ocl/1.1.0/oclstdlib.ecore#/0/OclAny_Class/=">
        <source xsi:type="ocl.ecore:PropertyCallExp" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
            referredProperty="ecore:EReference /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/sit">
          <source xsi:type="ocl.ecore:VariableExp" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"
              referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/9/@specification/@contextVariable"/>
        </source>
        <argument xsi:type="ocl.ecore:VariableExp" name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
            referredVariable="/home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/9/@specification/@parameterVariable.0"/>
      </bodyExpression>
      <contextVariable xsi:type="ocl.ecore:Variable" name="self" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person"/>
      <parameterVariable xsi:type="ocl.ecore:Variable" name="b" eType="ecore:EClass /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Building"
          representedParameter="ecore:EParameter /home/martin/Projects/chimpanc/example/fsl-0.emf.ecore#/0/Person/pass/b"/>
    </specification>
  </ocl.ecore:Constraint>
</xmi:XMI>
